// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 0003_pre_go_acc_user_info_9999.sql

package database

import (
	"context"
	"database/sql"
)

const addUserAutoUserId = `-- name: AddUserAutoUserId :execresult
INSERT INTO ` + "`" + `pre_go_acc_user_info_9999` + "`" + ` (
    user_account, user_avatar, user_nickname, user_state, user_mobile, user_birthday, user_email, user_gender, user_is_authentication
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AddUserAutoUserIdParams struct {
	UserAccount          string
	UserAvatar           sql.NullString
	UserNickname         sql.NullString
	UserState            uint8
	UserMobile           sql.NullString
	UserBirthday         sql.NullTime
	UserEmail            sql.NullString
	UserGender           sql.NullInt16
	UserIsAuthentication uint8
}

func (q *Queries) AddUserAutoUserId(ctx context.Context, arg AddUserAutoUserIdParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addUserAutoUserId,
		arg.UserAccount,
		arg.UserAvatar,
		arg.UserNickname,
		arg.UserState,
		arg.UserMobile,
		arg.UserBirthday,
		arg.UserEmail,
		arg.UserGender,
		arg.UserIsAuthentication,
	)
}

const addUserHaveUserId = `-- name: AddUserHaveUserId :execresult
INSERT INTO ` + "`" + `pre_go_acc_user_info_9999` + "`" + ` (
    user_id, user_account, user_avatar, user_nickname, user_state, user_mobile, user_birthday, user_email, user_gender, user_is_authentication
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AddUserHaveUserIdParams struct {
	UserID               uint64
	UserAccount          string
	UserAvatar           sql.NullString
	UserNickname         sql.NullString
	UserState            uint8
	UserMobile           sql.NullString
	UserBirthday         sql.NullTime
	UserEmail            sql.NullString
	UserGender           sql.NullInt16
	UserIsAuthentication uint8
}

func (q *Queries) AddUserHaveUserId(ctx context.Context, arg AddUserHaveUserIdParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addUserHaveUserId,
		arg.UserID,
		arg.UserAccount,
		arg.UserAvatar,
		arg.UserNickname,
		arg.UserState,
		arg.UserMobile,
		arg.UserBirthday,
		arg.UserEmail,
		arg.UserGender,
		arg.UserIsAuthentication,
	)
}

const editUserByUserId = `-- name: EditUserByUserId :execresult
UPDATE ` + "`" + `pre_go_acc_user_info_9999` + "`" + `
SET user_nickname = ?, user_avatar = ?, user_mobile = ?, user_gender = ?, user_birthday = ?, user_email = ?, updated_at = NOW()
WHERE user_id = ? AND user_is_authentication = 1
`

type EditUserByUserIdParams struct {
	UserNickname sql.NullString
	UserAvatar   sql.NullString
	UserMobile   sql.NullString
	UserGender   sql.NullInt16
	UserBirthday sql.NullTime
	UserEmail    sql.NullString
	UserID       uint64
}

func (q *Queries) EditUserByUserId(ctx context.Context, arg EditUserByUserIdParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, editUserByUserId,
		arg.UserNickname,
		arg.UserAvatar,
		arg.UserMobile,
		arg.UserGender,
		arg.UserBirthday,
		arg.UserEmail,
		arg.UserID,
	)
}

const getUser = `-- name: GetUser :one
SELECT user_id, user_account, user_avatar, user_nickname, user_state, user_mobile, user_birthday, user_email, user_gender, user_is_authentication, created_at, updated_at
FROM ` + "`" + `pre_go_acc_user_info_9999` + "`" + `
WHERE user_id = ? 
LIMIT 1
`

type GetUserRow struct {
	UserID               uint64
	UserAccount          string
	UserAvatar           sql.NullString
	UserNickname         sql.NullString
	UserState            uint8
	UserMobile           sql.NullString
	UserBirthday         sql.NullTime
	UserEmail            sql.NullString
	UserGender           sql.NullInt16
	UserIsAuthentication uint8
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
}

func (q *Queries) GetUser(ctx context.Context, userID uint64) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, userID)
	var i GetUserRow
	err := row.Scan(
		&i.UserID,
		&i.UserAccount,
		&i.UserAvatar,
		&i.UserNickname,
		&i.UserState,
		&i.UserMobile,
		&i.UserBirthday,
		&i.UserEmail,
		&i.UserGender,
		&i.UserIsAuthentication,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT user_id, user_account, user_avatar, user_nickname, user_state, user_mobile, user_birthday, user_email, user_gender, user_is_authentication, created_at, updated_at
FROM ` + "`" + `pre_go_acc_user_info_9999` + "`" + `
WHERE user_id IN (?)
`

type GetUsersRow struct {
	UserID               uint64
	UserAccount          string
	UserAvatar           sql.NullString
	UserNickname         sql.NullString
	UserState            uint8
	UserMobile           sql.NullString
	UserBirthday         sql.NullTime
	UserEmail            sql.NullString
	UserGender           sql.NullInt16
	UserIsAuthentication uint8
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
}

func (q *Queries) GetUsers(ctx context.Context, userID uint64) ([]GetUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersRow
	for rows.Next() {
		var i GetUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserAccount,
			&i.UserAvatar,
			&i.UserNickname,
			&i.UserState,
			&i.UserMobile,
			&i.UserBirthday,
			&i.UserEmail,
			&i.UserGender,
			&i.UserIsAuthentication,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUser = `-- name: RemoveUser :exec
DELETE FROM ` + "`" + `pre_go_acc_user_info_9999` + "`" + `
WHERE user_id = ?
`

func (q *Queries) RemoveUser(ctx context.Context, userID uint64) error {
	_, err := q.db.ExecContext(ctx, removeUser, userID)
	return err
}

const findUsers = `-- name: findUsers :many
SELECT user_id, user_account, user_nickname, user_avatar, user_state, user_mobile, user_gender, user_birthday, user_email, user_is_authentication, created_at, updated_at
FROM ` + "`" + `pre_go_acc_user_info_9999` + "`" + `
WHERE user_account LIKE ? OR user_nickname LIKE ?
`

type findUsersParams struct {
	UserAccount  string
	UserNickname sql.NullString
}

func (q *Queries) findUsers(ctx context.Context, arg findUsersParams) ([]PreGoAccUserInfo9999, error) {
	rows, err := q.db.QueryContext(ctx, findUsers, arg.UserAccount, arg.UserNickname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PreGoAccUserInfo9999
	for rows.Next() {
		var i PreGoAccUserInfo9999
		if err := rows.Scan(
			&i.UserID,
			&i.UserAccount,
			&i.UserNickname,
			&i.UserAvatar,
			&i.UserState,
			&i.UserMobile,
			&i.UserGender,
			&i.UserBirthday,
			&i.UserEmail,
			&i.UserIsAuthentication,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: listUsers :many
SELECT user_id, user_account, user_nickname, user_avatar, user_state, user_mobile, user_gender, user_birthday, user_email, user_is_authentication, created_at, updated_at
FROM ` + "`" + `pre_go_acc_user_info_9999` + "`" + `
LIMIT ? OFFSET ?
`

type listUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) listUsers(ctx context.Context, arg listUsersParams) ([]PreGoAccUserInfo9999, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PreGoAccUserInfo9999
	for rows.Next() {
		var i PreGoAccUserInfo9999
		if err := rows.Scan(
			&i.UserID,
			&i.UserAccount,
			&i.UserNickname,
			&i.UserAvatar,
			&i.UserState,
			&i.UserMobile,
			&i.UserGender,
			&i.UserBirthday,
			&i.UserEmail,
			&i.UserIsAuthentication,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
