version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_con
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci SET GLOBAL host_cache_size=0
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: shopdevgo
      MYSQL_USER: levanhieu
      MYSQL_PASSWORD: levanhieu1234
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  redis:
    image: redis:7.0
    container_name: redis_con
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  app:
    build: .
    container_name: my_app
    networks:
      - app-network
    depends_on:
      - redis
      - mysql
    ports:
      - "8002:8001"

volumes:
  mysql_data:
  redis_data:

networks:
  app-network:
    driver: bridge
